plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

group = 'com.minikkurtcuk'
version = '1.0.0-optimized'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    copyIdeResources = true
    runs {
        client { workingDirectory project.file('run'); property 'forge.logging.markers', 'REGISTRIES'; property 'forge.logging.console.level', 'info'; mods { aivillager { source sourceSets.main } } }
        server { workingDirectory project.file('run'); property 'forge.logging.markers', 'REGISTRIES'; property 'forge.logging.console.level', 'info'; mods { aivillager { source sourceSets.main } } }
    }
}

repositories { }

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.20'
}

jar { archiveBaseName = 'IntelligentVillagers-Optimized'; manifest { attributes(['Specification-Title':'Intelligent Villagers Optimized','Specification-Version':'1','Implementation-Title':'AI Villager Optimized','Implementation-Version':project.version]) } }

jar.finalizedBy('reobfJar')
